### ISSUE TITLE
Set Up Database for Course Information

### ISSUE THREAD

**Issue by Artlfmj** [Artlfmj/course-manager#1]
Create the database structure and schemas necessary to store information about the courses. Define the fields for course title, description, duration, difficulty level, and any other relevant information.

**Comment by samratghosh291** [comment]
please assign me to this issues

**Comment by Artlfmj** [comment]
> please assign me to this issues

Done :)

**Comment by samratghosh291** [comment]
what should I do? just create a schema of the above features for MongoDB.

**Comment by Artlfmj** [comment]
Create models, connection features. There isnt much to do on this part :)

**Comment by Artlfmj** [comment]
If you need to discuss more in depth, I suggest you join the Discord so that we can chat in a more realtimeway

**Comment by samratghosh291** [comment]
ok sure
