### ISSUE TITLE
Design Certificate Templates

### ISSUE THREAD

**Issue by Artlfmj** [Artlfmj/course-manager#16]
Design visually appealing certificate templates that can be customized with course details and user information upon completion.

**Comment by ira-mane** [comment]
Hello , I would love to design certificate template , Could you Please assign me this issue. 
Thankyou !!

**Comment by Artlfmj** [comment]
Done @ira-mane , don't hesitate to join the discord :)

**Comment by hollermay** [comment]
Hey there, I would also like work and design templates for certificates as being into graphic designing for the last three years, I have designed a lot of certificates for my open source society. I hope you won't mind giving me a shot to it :)

**Comment by Artlfmj** [comment]
@hollermay there you go

**Comment by hollermay** [comment]
how do you want them in a document format or a blank certificate? where I could placeholder as you have mentioned design and feature here

**Comment by Artlfmj** [comment]
Best is either pdf or image template with also canvas directions on what to place

**Comment by hollermay** [comment]
Okay

**Comment by hollermay** [comment]
> Best is either pdf or image template with also canvas directions on what to place

So for that, I'll commit one file to the code with 10 templates.

**Comment by Artlfmj** [comment]
Go ahead

**Comment by hollermay** [comment]
@Artlfmj please review my pull request and accept it, currently I could design 6 templates, I'll add 4 later on

**Comment by Artlfmj** [comment]
🕒 **Reminder: 24-Hour Assignment Commit Deadline** 🕒

Hello @ira,

Thank you for accepting the assignment for this issue. We appreciate your willingness to contribute to the Course Manager project!

This is a friendly reminder that you have a 24-hour window to make your initial commit to this issue. If you are unable to make the commit within this timeframe, your assignment will be automatically removed to allow other contributors to work on it.

Please feel free to reach out if you have any questions or need assistance with the issue. We're here to help!

Happy coding! 🚀

**Comment by ira-mane** [comment]
@Artlfmj I have already added designed template file in assets folder .Please have a look and Please let me know if there's' some issue.

**Comment by Artlfmj** [comment]
> @Artlfmj I have already added designed template file in assets folder .Please have a look and Please let me know if there's' some issue.

Sorry for the confusion ❤️

**Comment by Artlfmj** [comment]
@ira-mane @hollermay do you want me to keep this open or not?
