### ISSUE TITLE
Application not running

### ISSUE THREAD

**Issue by KhuzaimaNawab** [Artlfmj/course-manager#21]
Application have bugs in it and does not run.

**To Reproduce**
1. Go to 'terminal'
2. Write 'node app.'
3. See error

**Expected behavior**
Should show me login screen.

**Screenshots**
![Screenshot 2023-10-01 184628](https://github.com/Artlfmj/course-manager/assets/63063076/e2ad2c9a-85ca-4d5b-a1c6-07e82636e09f)

**Comment by Artlfmj** [comment]
Have u made sure to pull latest version

**Comment by KhuzaimaNawab** [comment]
Yes

**Comment by Artlfmj** [comment]
Could you join the Discord so you can show me?

**Comment by Artlfmj** [comment]
Should be fixed by https://github.com/Artlfmj/course-manager/commit/56a4d8467f32e7e5c07c620694d462e40a8b2792
