### ISSUE TITLE
Add setup.md file

### ISSUE THREAD

**Issue by 1-ankush-1** [Artlfmj/course-manager#30]
**Is your feature request related to a problem? Please describe.**
The `setup.md` file appears to be missing from the repository. This file is typically used to provide instructions on how to set up and run the project locally. Without it, contributors might have a hard time getting started with contributing to the project.

**Describe the solution you'd like**
You need to create a step by step instruction of how user can run this project locally.

**Additional context**
Assign this to me .

**Comment by Artlfmj** [comment]
Done

**Comment by Artlfmj** [comment]
Resolved by #41
