### ISSUE TITLE
Organizing Backend files

### ISSUE THREAD

**Issue by NandanUpadhyay2611** [Artlfmj/course-manager#32]
**Is your feature request related to a problem? Please describe.**

I went through the repo, and noticed that app.js is too much loaded.(i.e contains a lot of code) and overall backend is unorganized.

Solution: 
So, I will be organizing the backend code like different folders and files for controllers, routes , and more organized app.js(so that it contains only app.listen() and some important imports only)

**Additional context**

Kindly Assign this task to me! please!

**Comment by Artlfmj** [comment]
Assigned you, if you aren't on the discord already don't hesitate to join

**Comment by Artlfmj** [comment]
🕒 **Reminder: 24-Hour Assignment Commit Deadline** 🕒

Hello @NandanUpadhyay2611 ,

Thank you for accepting the assignment for this issue. We appreciate your willingness to contribute to the Course Manager project!

This is a friendly reminder that you have a 24-hour window to make your initial commit to this issue. If you are unable to make the commit within this timeframe, your assignment will be automatically removed to allow other contributors to work on it.

Please feel free to reach out if you have any questions or need assistance with the issue. We're here to help!

Happy coding! 🚀

**Comment by Artlfmj** [comment]
#38 both should work together :)

**Comment by Dharansh-Neema** [comment]
@NandanUpadhyay2611 I have created config folder for DB config and passport config so make your routes and controllers accordingly.

**Comment by NandanUpadhyay2611** [comment]
@Dharansh-Neema Let him accept your PR then. Actually I have organized everything already ! But not a problem ! Let your PR get merge then I will be updating my fork, and make changes accordingly.!

**Comment by NandanUpadhyay2611** [comment]
@Artlfmj kind request to you! Please let me complete working. Untill don't assign same issue to others! It becomes a little more hectic! I hope you get it :)

**Comment by Dharansh-Neema** [comment]
Thankyou so much @NandanUpadhyay2611

**Comment by Artlfmj** [comment]
> @Artlfmj kind request to you! Please let me complete working. Untill don't assign same issue to others! It becomes a little more hectic! I hope you get it :)

🫡👍

**Comment by NandanUpadhyay2611** [comment]
hey @Artlfmj ! i am encountering a new error while running the app. especially when sending post request to "/register".
it is something related to csrf ( i am attaching screen capture)  , which i am not aware of what it is .
And that's why it is taking me longer !
If you want i can create issue for the same !
rest Everything is perfectly fine with my commits only this csrf thing!

**Comment by Artlfmj** [comment]
You can work on a fix :), I believe someone broke csrf with their prs

**Comment by NandanUpadhyay2611** [comment]
I don't know the solution for this! i Tried searching on the internet but can't get any easy fix ! so I am creating an issue for the same!
And should i raise pr for my commits? It is all fine except this! so if someone knows the solution you can assign the issue!

**Comment by Artlfmj** [comment]
Sure, i'll merge yours

**Comment by Artlfmj** [comment]
wait wdym by raise pr

**Comment by NandanUpadhyay2611** [comment]
create/make/open ??

**Comment by Artlfmj** [comment]
Oh yeah sorry, go ahead

**Comment by NandanUpadhyay2611** [comment]
Thanks!

**Comment by NandanUpadhyay2611** [comment]
#49

**Comment by Artlfmj** [comment]
@NandanUpadhyay2611 is this issue finished?

**Comment by NandanUpadhyay2611** [comment]
Ya !

**Comment by Artlfmj** [comment]
> Ya !

Awesome, don't hesitate to work on new stuff
