### ISSUE TITLE
Structuring the App.js file 

### ISSUE THREAD

**Issue by Dharansh-Neema** [Artlfmj/course-manager#38]
**Is your feature request related to a problem? Please describe.**
I will be moving out db config and passport.js connection.

Kind of like this:
<img width="445" alt="image" src="https://github.com/Artlfmj/course-manager/assets/89770584/e42a032e-a8d4-4550-883f-4c948bb36225">

**Comment by Dharansh-Neema** [comment]
For this issue a PR #39  is been created.

**Comment by Artlfmj** [comment]
Resolved by #39
