### ISSUE TITLE
Providing setup instruction.

### ISSUE THREAD

**Issue by Dharansh-Neema** [Artlfmj/course-manager#40]
Editing the readme.md file to provide comprehensive setup instructions for new contributors. The inclusion of clear setup instructions is essential for ensuring a seamless and efficient development process within the repository.

**Comment by Sushannt** [comment]
please assign this to me.

**Comment by Artlfmj** [comment]
@Sushannt gi ahead, but please make it into a Setup.md file

**Comment by Artlfmj** [comment]
Wait this is a duplicate of #30

**Comment by Artlfmj** [comment]
@Sushannt please ask to be assigned to another issue :)
