### ISSUE TITLE
Bug report: Invalid Csrf token 

### ISSUE THREAD

**Issue by NandanUpadhyay2611** [Artlfmj/course-manager#48]
**Describe the bug**
Error is something related to csrf ! it exits "forbidden Error: invalid csrf token"

**To Reproduce**
1. Run the server (i.e app.js)
2. Try sending post requests to "/register" or any other route which involves csrf. 
3. See error

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : Chrome
 

**Additional context**
![app js - course manager-clonedoriginal repo - Visual Studio Code 10_5_2023 8_31_35 PM](https://github.com/Artlfmj/course-manager/assets/112714279/3b2f903c-5023-4f58-ad05-ae5672a46e25)
![app js - course manager-clonedoriginal repo - Visual Studio Code 10_5_2023 8_31_46 PM](https://github.com/Artlfmj/course-manager/assets/112714279/ffb43623-ba6f-462c-bca6-43bb624e9afc)

**Comment by Artlfmj** [comment]
Fixed by https://github.com/Artlfmj/course-manager/commit/5b5e95b495f27bfeb4b42b6ee36536a6d19aaefb
