### ISSUE TITLE
Update package.json

### ISSUE THREAD

**Issue by neenad99** [Artlfmj/course-manager#50]
**Is your feature request related to a problem? Please describe.**
currently in package.json there are no scripts added in scripts section to run application 

**Describe the solution you'd like**
update package.json to add scripts to start application depending on runtime environment dev,production etc

**Additional context**
<img width="1271" alt="image" src="https://github.com/Artlfmj/course-manager/assets/47708101/a0caab47-238c-41d0-8a96-0f4caf46721a">

**Comment by Artlfmj** [comment]
This should be a feature included in another pr, it isn't enough for a full pr

**Comment by Ayush-Vish** [comment]
@Artlfmj   Please assign me this issue .

**Comment by Artlfmj** [comment]
@Ayush-Vish assigned
