### ISSUE TITLE
Add validation for username and password

### ISSUE THREAD

**Issue by malay5** [Artlfmj/course-manager#55]
**Is your feature request related to a problem? Please describe.**
Yes, we need to have concise rules and validations in check, in order to onboard a user

**Describe the solution you'd like**
I would like to put regex for email in the signup page email input, as well as password validation, where the password should be of at least 6 characters

**Comment by malay5** [comment]
Can you please assign this issue to me

**Comment by Artlfmj** [comment]
@malay5 even though this is very important, try working on already opened issues ;)

**Comment by malay5** [comment]
Thanks a lot!
