### ISSUE TITLE
Ensure Responsiveness

### ISSUE THREAD

**Issue by Artlfmj** [Artlfmj/course-manager#9]
Optimize the user interface to be responsive, making it accessible and usable on various devices, including desktops, tablets, and mobile phones.

**Comment by parthksingh1** [comment]
Please assign me this issue I will Implement responsiveness @Artlfmj

**Comment by Artlfmj** [comment]
Added @parthksingh1, don't hesitate to join the discord :)

**Comment by Artlfmj** [comment]
🕒 **Reminder: 24-Hour Assignment Commit Deadline** 🕒

Hello @parthksingh1 ,

Thank you for accepting the assignment for this issue. We appreciate your willingness to contribute to the Course Manager project!

This is a friendly reminder that you have a 24-hour window to make your initial commit to this issue. If you are unable to make the commit within this timeframe, your assignment will be automatically removed to allow other contributors to work on it.

Please feel free to reach out if you have any questions or need assistance with the issue. We're here to help!

Happy coding! 🚀

**Comment by Artlfmj** [comment]
Resolved by #36
